secrets:
  company:
    cert: "BASE64"
  agent:
    cert: "BASE64"
    key: "BASE64"

kafka:
  broker: kafka1.mgmt.umh.app:31092
  httpBroker: https://kafka1.mgmt.umh.app

opcua:
  devices:
    - endpoint: "opc.tcp://united-manufacturing-hub-opcuasimulator-service:46010"
      keyname: "opcua-simulator-ns2-iot-sensors"
      nodes:
        - nodeid: "ns=2;s=IotSensors"
          tagName: "pressure"
          enterprise: "umh"
          site: "cologne"
          area: "unicorn"
          line: "some-line"
          workCell: "some-workcell"
          originId: "plc-01"

