apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: managementconsolecompanion-rolebinding
  namespace: mgmt-companion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: managementconsolecompanion-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: mgmt-companion
