apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mgmt-companion-default-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: default
    namespace: mgmt-companion
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
