apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-datasource
  namespace: mgmt-companion
data:
  datasource.yaml: |-
    benthos:
      opcua:
        devices:
{{- range .Values.opcua.devices }}
          - endpoint: {{ .endpoint }}
            keyname: {{ .keyname }}
            nodes:
{{- range .nodes }}
              - id: {{ . }}
{{- end }}
{{- end }}
