apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mgmt-companion-helm-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: mgmt-companion-helm
    namespace: mgmt-companion
roleRef:
  kind: ClusterRole
  name: mgmt-companion-helm
  apiGroup: rbac.authorization.k8s.io
