apiVersion: v1
kind: Secret
metadata:
  name: certs-secrets
  namespace: mgmt-companion
type: Opaque
data:
  company.crt: INVALID_REPLACE_ME
  agent.crt: INVALID_REPLACE_ME
  agent.key: INVALID_REPLACE_ME
