apiVersion: v1
kind: Secret
metadata:
  name: certs-secrets
  namespace: mgmt-companion
type: Opaque
data:
  company.crt: {{.Values.secrets.company.cert}}
  agent.crt:{{.Values.secrets.agent.cert}}
  agent.key: {{.Values.secrets.agent.key}}
